@Library("mylibrary")_
node("built-in")
{
        stage('ContinuousDownload_master')
        {
    		scripMulti.newGit("https://github.com/intelliqittrainings/maven.git")
		}
        stage('ContinuousBuild_master')
        {
           scripMulti.newMaven()
		}
        stage('ContinuousDeployment_master')
        {
	    	scripMulti.newDeploy("${env.WORKSPACE}","172.31.85.255","testapp4")
	    }
        stage('ContinuousTesting_master')
        {
        	scripMulti.newGit("https://github.com/intelliqittrainings/FunctionalTesting.git")
			scripMulti.newTesting("${env.WORKSPACE}")
		}
	    stage('ContinuousDelivery_master')
	    {
			multi.newDeploy("${env.WORKSPACE}","172.31.94.84","prodapp4")
		}
}
