@Library("mylibrary")_
node("built-in")
{
        stage('ContinuousDownload_master')
        {
    		scripMulti.newGit("https://github.com/intelliqittrainings/maven.git")
		}
        stage('ContinuousBuild_master')
        {
           scripMulti.newMaven()
		}
}
